arb-dir: lib/l10n
template-arb-file: app_ar.arb
template-en-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
untranslated-messages-file: lib/l10n/untranslated.txt
synthetic-package: false
nullable-getter: false
