name: qanet
description: "A Quran application built with Flutter."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Icons
  dropdown_button2: any
  flutter_screenutil: any
  cupertino_icons: ^1.0.8
  font_awesome_flutter: any

  # State Management
  provider: any

  # Networking
  http: ^0.13.6
  connectivity_plus: any

  # Local Data Storage
  hive: ^2.2.3
  path_provider: any
  hive_flutter: ^1.1.0
  shared_preferences: any

  # Audio Playback
  audioplayers: any

  # Internationalization
  intl: any
  easy_localization: ^3.0.3

dev_dependencies:
  # Code Generation
  build_runner: ^2.1.7
  hive_generator: ^2.0.0

  # Flutter Tools
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/translations/

  fonts:
    - family: Uthmani
      fonts:
        - asset: assets/fonts/UthmanTNB_v2-0.ttf

flutter_launcher_icons:
  ios: true
  android: true
  image_path: "assets/images/logo.png"
