name: qanet
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.6
  path_provider:
  provider:
  cupertino_icons: ^1.0.8
  audioplayers:
  intl:
  font_awesome_flutter:
  shared_preferences:
  flutter_screenutil:
  dropdown_button2:
dev_dependencies:
  hive_generator: ^2.0.0
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  #generate: true 

  assets:
    - assets/images/
    - assets/fonts/
    - assets/translations/


  fonts:
    - family: Uthmani
      fonts:
        - asset: assets/fonts/UthmanTNB_v2-0.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
